language: node_js

node_js:
  - "6"

sudo: false

install:
  - sudo echo "localhost gitlalb.mock github.mock" >> /etc/hosts
  - npm install

script:
  - npm test
  - npm run coverage
  - npm run checkCoverage
